<a href="https://colab.research.google.com/github/SzymonKon/DataSciencePractice/blob/main/algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v1 = np.array([2,6])

In [3]:
v1

array([2, 6])

In [4]:
np.linalg.norm(v1)

6.324555320336759

In [6]:
v2 = np.array([3,-1])

In [7]:
np.linalg.norm(v2-v1)

7.0710678118654755

MNOŻENIE MACIERZY

In [17]:
A = np.array([[5,1,0], [-2,4,-1], [4,1,2]])
A

array([[ 5,  1,  0],
       [-2,  4, -1],
       [ 4,  1,  2]])

In [11]:
B = np.array([[2,5],[4,-1],[0,-1]])
B

array([[ 2,  5],
       [ 4, -1],
       [ 0, -1]])

In [14]:
Z = np.dot(A,B)
Z

array([[ 14,  24],
       [ 12, -13]])

In [18]:
np.linalg.det(A)

45.000000000000014

In [19]:
np.trace(A)

11

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [24]:
C = np.linalg.inv(A)
C

array([[ 0.2       , -0.04444444, -0.02222222],
       [ 0.        ,  0.22222222,  0.11111111],
       [-0.4       , -0.02222222,  0.48888889]])

In [25]:
np.dot(A,C)

array([[ 1.00000000e+00, -2.77555756e-17, -1.38777878e-17],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -6.93889390e-18,  1.00000000e+00]])

In [26]:
Q = np.array([[4,5],[1,-2]])
Q

array([[ 4,  5],
       [ 1, -2]])

In [27]:
W = np.array([-2,3])
W

array([-2,  3])

In [28]:
Q_inv = np.linalg.inv(Q)

In [29]:
Z = np.dot(Q_inv, W)
Z

array([ 0.84615385, -1.07692308])