<a href="https://colab.research.google.com/github/SzymonKon/DataSciencePractice/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
dir(np)

1D ARRAY

In [ ]:
x = np.array([1,4,5])
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(3,)

In [ ]:
x.size

3

In [ ]:
x.dtype

dtype('int64')

2D ARRAY


In [ ]:
x = np.array([[1,0],[-5,4]])
x

array([[ 1,  0],
       [-5,  4]])

In [ ]:
x.ndim

2

In [ ]:
x.size

4

In [ ]:
x.shape

(2, 2)

3D ARRAY

In [ ]:
x = np.array(
    [[[1,4,7], [2,0,-5]],
    [[3,8,7], [2,0,11]],
     [[3,6,5], [0,9,0]]]
)
x

array([[[ 1,  4,  7],
        [ 2,  0, -5]],

       [[ 3,  8,  7],
        [ 2,  0, 11]],

       [[ 3,  6,  5],
        [ 0,  9,  0]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

In [ ]:
np.zeros(shape = (2,5), dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
np.ones(shape = (4,4), dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
np.full(shape = (3,4), fill_value=2137, dtype=int)

array([[2137, 2137, 2137, 2137],
       [2137, 2137, 2137, 2137],
       [2137, 2137, 2137, 2137]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start = 0, stop = 11, step = 1, dtype=int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(start=0, stop=50, num=5, dtype=int)

array([ 0, 12, 25, 37, 50])

In [ ]:
A = np.array([1,4,6,7,5,4,3,8,0])

In [ ]:
A

array([1, 4, 6, 7, 5, 4, 3, 8, 0])

In [ ]:
A.reshape((-1,3))

array([[1, 4, 6],
       [7, 5, 4],
       [3, 8, 0]])

In [ ]:
B = np.array([1,4,7])
B

array([1, 4, 7])

In [ ]:
np.ones(shape = (4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
B.reshape((3,-1))

array([[1],
       [4],
       [7]])

In [3]:
A = np.array([3,6,7,2])

In [4]:
A


array([3, 6, 7, 2])

In [5]:
A.reshape(2,-1)

array([[3, 6],
       [7, 2]])

In [6]:
B = np.ones(shape = (3,5), dtype=int)
B

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

MNOŻENIE TABLIC

In [7]:
A = np.array([1,6,-2])
B = np.array([1,8,0])

In [8]:
print(A*B)

[ 1 48  0]


In [9]:
A @ B

49

In [15]:
X = np.array([[3,0], [6,12]])

In [16]:
Y = np.array([[4,1], [-4,9]])

In [12]:
X+Y

array([[ 7,  9,  1],
       [ 6, -3,  7]])

In [13]:
X/Y

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 0.75      ,  3.5       ,  0.        ],
       [        inf, -0.25      , -0.22222222]])

In [17]:
np.dot(X,Y)

array([[ 12,   3],
       [-24, 114]])

In [18]:
X.dot(Y)

array([[ 12,   3],
       [-24, 114]])

In [19]:
X @ Y

array([[ 12,   3],
       [-24, 114]])

GENERATOR LICZB PSEUDOLOSOWYCH

In [20]:
np.random.seed()

In [21]:
np.random.randn()

1.125536694976503

In [22]:
np.random.randn(2,4)

array([[-0.04429322,  0.5795819 ,  0.99667013, -0.17331476],
       [ 0.71891476, -0.39799534, -0.49057739,  0.49707556]])

In [23]:
np.random.rand()

0.6619254923538511

In [24]:
np.random.rand(2)

array([0.88410535, 0.44507588])

In [25]:
np.random.rand(2,3)

array([[0.66337178, 0.60283257, 0.98153993],
       [0.60025746, 0.3017652 , 0.68253184]])

In [26]:
np.random.randint(2,10,5)

array([8, 2, 2, 3, 7])

In [27]:
np.random.choice(["barca", "juve", "napoli", "real", "monaco"],size=3)

array(['juve', 'monaco', 'juve'], dtype='<U6')

In [39]:
np.random.choice(["barca", "juve", "napoli", "real", "monaco"],size=3,)

array(['barca', 'barca', 'juve'], dtype='<U6')

In [29]:
A= np.array(["barca", "juve", "napoli", "real", "monaco", "borussia", "city", "valencia"])

In [30]:
np.random.shuffle(A)

In [31]:
A


array(['borussia', 'barca', 'real', 'city', 'juve', 'monaco', 'valencia',
       'napoli'], dtype='<U8')

PODSTAWOWE FUNKCJE

In [40]:
np.exp(1)

2.718281828459045

In [41]:
np.exp(2)

7.38905609893065

In [42]:
np.sqrt(4)

2.0

In [44]:
np.all([1,6,3,10])

True

In [45]:
np.any([1,0,4,-2])

True

In [46]:
A=np.random.rand(8)
A

array([0.4657962 , 0.42964526, 0.05935315, 0.33160161, 0.20576964,
       0.91182061, 0.18600001, 0.70074936])

In [47]:
np.argmax(A)

5

In [48]:
np.argmin(A)

2

In [49]:
np.max(A)

0.9118206076384928

In [50]:
np.min(A)

0.05935315274729025

In [51]:
np.argsort(A)

array([2, 6, 4, 3, 1, 0, 7, 5])

In [52]:
np.sort(A)

array([0.05935315, 0.18600001, 0.20576964, 0.33160161, 0.42964526,
       0.4657962 , 0.70074936, 0.91182061])

In [53]:
np.mean(A)

0.4113419790661441

In [54]:
np.median(A)

0.38062343244384744

In [55]:
np.std(A)

0.26477098869174215

In [56]:
A=np.arange(12)

In [60]:
A=A.reshape(3,4)

In [61]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
A[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [63]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
for row in A:
  print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [65]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11


In [66]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
A.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [68]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [73]:
B=np.arange(-5, 5, 0.5)
B

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [74]:
B[B>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [76]:
B>0

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [77]:
np.bitwise_and(B<-2, B>2)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [78]:
np.bitwise_and(B>-2, B<2)

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [79]:
B[np.bitwise_and(B>-2, B<2)]

array([-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5])